### ISSUE TITLE
无法运行啊

### ISSUE THREAD

**Issue by baiyibing123** [xuyaoqiang/elastalert-dingtalk-plugin#1]
![image](https://user-images.githubusercontent.com/14048464/62362975-c0e8bc80-b550-11e9-898c-d0576fb0c24a.png)

**Comment by PonusJang** [comment]
me too

**Comment by nsano-rururu** [comment]
filebeat7.5.1+elasticsearch7.5.1+elastAlert0.2.1+elastalert-dingtalk-plugin实现日志监控钉钉告警
https://blog.csdn.net/a807719447/article/details/103929104
